pairs:
  - sample: CCHFV_DEMO_01
    r1: data-example/fastq/CCHFV_DEMO_01_R1.fastq
    r2: data-example/fastq/CCHFV_DEMO_01_R2.fastq

discovery:
  min_len_contig: 300
  blast_remote: true
  blast_db: nt
  top_hits: 25

phylogeny:
  bootstrap: 1000
  use_model_finder: true
  min_depth_consensus: 10

context:
  per_segment_hits: 25
