pairs:
  - sample: CCHF_2022_ISB_01
    r1: data-private/CCHF_2022_ISB_01_R1.fastq.gz
    r2: data-private/CCHF_2022_ISB_01_R2.fastq.gz

discovery:
  min_len_contig: 300
  blast_remote: true
  blast_db: nt
  top_hits: 25

phylogeny:
  bootstrap: 1000
  use_model_finder: true
  min_depth_consensus: 10

context:
  per_segment_hits: 25
